### ISSUE TITLE
AddressSanitizer: global-buffer-overflow: ArrayIndexOutOfBounds @IUnknown.h:49 (METHODS[_myHandlerCount])

### ISSUE THREAD

**Issue by dwrobel** [WebPlatformForEmbedded/Thunder#120]
branch: master (4caaa1e27b9ead0432ffdcb56986d99cc9727c10), wpewebkit: wpe-2.22
compiled with: -fsanitize=address
reproducibility: 100%

Aborts at very early stage of WPEFramework startup _(acctually in a static-initialization)_ as following:
```
=================================================================
==19157==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f13851c77e8 at pc 0x7f13851857cb bp 0x7f1388ffaf60 sp 0x7f1388ffaf50
READ of size 8 at 0x7f13851c77e8 thread T2
    #0 0x7f13851857ca in WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods>::UnknownStubType() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xdb7ca)
    #1 0x7f138517f249 in void WPEFramework::RPC::Administrator::Announce<OCDM::ISessionExt, WPEFramework::SessionExtProxy, WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods> >() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xd5249)
    #2 0x7f1385175fa3 in WPEFramework::Instantiation::Instantiation() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xcbfa3)
    #3 0x7f138516a244 in __static_initialization_and_destruction_0(int, int) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xc0244)
    #4 0x7f138516a509 in _GLOBAL__sub_I_ProxyStubs.cpp (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xc0509)
    #5 0x7f138e19bde9 in call_init /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-init.c:72
    #6 0x7f138e19bee9 in call_init /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-init.c:118
    #7 0x7f138e19bee9 in _dl_init /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-init.c:119
    #8 0x7f138e19fece in dl_open_worker /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-open.c:506
    #9 0x7f138c9e7066 in __GI__dl_catch_exception /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-error-skeleton.c:196
    #10 0x7f138e19f73d in _dl_open /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-open.c:588
    #11 0x7f138d395399 in dlopen_doit /usr/src/debug/glibc-2.28-95-g7423da211d/dlfcn/dlopen.c:66
    #12 0x7f138c9e7066 in __GI__dl_catch_exception /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-error-skeleton.c:196
    #13 0x7f138c9e7102 in __GI__dl_catch_error /usr/src/debug/glibc-2.28-95-g7423da211d/elf/dl-error-skeleton.c:215
    #14 0x7f138d395b08 in _dlerror_run /usr/src/debug/glibc-2.28-95-g7423da211d/dlfcn/dlerror.c:163
    #15 0x7f138d395439 in __dlopen /usr/src/debug/glibc-2.28-95-g7423da211d/dlfcn/dlopen.c:87
    #16 0x7f138d42a033  (/lib64/libasan.so.5+0x90033)
    #17 0x7f138ce54816 in WPEFramework::Core::Library::Library(char const*) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libWPEFrameworkCore.so.1+0xaa816)
    #18 0x68d76f in WPEFramework::PluginHost::Server::Service::CheckLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, unsigned int) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x68d76f)
    #19 0x68e252 in WPEFramework::PluginHost::Server::Service::AquireInterfaces() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x68e252)
    #20 0x663bce in WPEFramework::PluginHost::Server::Service::Activate(WPEFramework::PluginHost::IShell::reason) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x663bce)
    #21 0x7f138d2e5f35 in WPEFramework::PluginHost::IShell::Job::Dispatch() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libWPEFrameworkPlugins.so.1+0x11bf35)
    #22 0x66daf2 in WPEFramework::Core::Job::Dispatch() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x66daf2)
    #23 0x6f373a in WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>::Worker() (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6f373a)
    #24 0x7f138cea0c2b in WPEFramework::Core::Thread::StartThread(WPEFramework::Core::Thread*) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libWPEFrameworkCore.so.1+0xf6c2b)
    #25 0x7f138c88758d in start_thread /usr/src/debug/glibc-2.28-95-g7423da211d/nptl/pthread_create.c:486
    #26 0x7f138c9aa682 in clone (/lib64/libc.so.6+0xfd682)

0x7f13851c77e8 is located 0 bytes to the right of global variable 'SessionExtStubMethods' defined in '/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/ocdm/ProxyStubs.cpp:814:26' (0x7f13851c7780) of size 104
0x7f13851c77e8 is located 56 bytes to the left of global variable 'OCDMProxyStubRegistration' defined in '/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/ocdm/ProxyStubs.cpp:1810:3' (0x7f13851c7820) of size 1
  'OCDMProxyStubRegistration' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libocdm.so.1+0xdb7ca) in WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods>::UnknownStubType()
Shadow bytes around the buggy address:
  0x0fe2f0a30ea0: 00 00 00 00 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0fe2f0a30eb0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe2f0a30ec0: 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x0fe2f0a30ed0: f9 f9 f9 f9 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
  0x0fe2f0a30ee0: 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
=>0x0fe2f0a30ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00[f9]f9 f9
  0x0fe2f0a30f00: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x0fe2f0a30f10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe2f0a30f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe2f0a30f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe2f0a30f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T2 created by T0 here:
    #0 0x7f138d3ecf63 in __interceptor_pthread_create (/lib64/libasan.so.5+0x52f63)
    #1 0x7f138cea05da in WPEFramework::Core::Thread::Thread(unsigned int, char const*) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/libWPEFrameworkCore.so.1+0xf65da)
    #2 0x6e329f in WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>::ThreadUnitType(WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int, char const*) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6e329f)
    #3 0x6db271 in void __gnu_cxx::new_allocator<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job> >::construct<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>, WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&>(WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>*, WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6db271)
    #4 0x6cd838 in void std::allocator_traits<std::allocator<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job> > >::construct<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>, WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&>(std::allocator<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job> >&, WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>*, WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6cd838)
    #5 0x6bb89b in void std::vector<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>, std::allocator<WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job> > >::emplace_back<WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&>(WPEFramework::Core::QueueType<WPEFramework::Core::Job>&, unsigned int const&, char const*&) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6bb89b)
    #6 0x6aaf03 in WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadPoolType(unsigned int, char const*) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x6aaf03)
    #7 0x687a77 in WPEFramework::PluginHost::Server::WorkerPoolImplementation::WorkerPoolImplementation(unsigned int) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x687a77)
    #8 0x669191 in WPEFramework::PluginHost::Server::Server(WPEFramework::PluginHost::Server::Config&, bool) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x669191)
    #9 0x64c59a in main (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/bin/WPEFramework-1.0.0+0x64c59a)
    #10 0x7f138c8d1412 in __libc_start_main ../csu/libc-start.c:308

==19157==ABORTING

```

Full gdb callstack:
```
(gdb) bt
#0  0x00007f138d4b25d0 in __sanitizer::Die() () at ../../../../libsanitizer/sanitizer_common/sanitizer_termination.cc:49
#1  0x00007f138d494ce5 in __asan::ScopedInErrorReport::~ScopedInErrorReport() (this=<optimized out>, __in_chrg=<optimized out>) at ../../../../libsanitizer/asan/asan_report.cc:181
#2  0x00007f138d494ce5 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) (pc=<optimized out>, bp=bp@entry=139721879564128, sp=sp@entry=139721879564112, addr=addr@entry=139721814341608, is_write=is_write@entry=false, access_size=access_size@entry=8, exp=0, fatal=false) at ../../../../libsanitizer/asan/asan_report.cc:397
#3  0x00007f138d4958ab in __asan::__asan_report_load8_noabort(__sanitizer::uptr) (addr=addr@entry=139721814341608) at ../../../../libsanitizer/asan/asan_rtl.cc:112
#4  0x00007f13851857cb in WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods>::UnknownStubType() (this=0x602000002d10) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/core/../com/IUnknown.h:49
#5  0x00007f138517f24a in WPEFramework::RPC::Administrator::Announce<OCDM::ISessionExt, WPEFramework::SessionExtProxy, WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods> >() (this=<optimized out>) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/core/../com/Administrator.h:71
#6  0x00007f1385175fa4 in WPEFramework::Instantiation::Instantiation() (this=0x7f13851c7820 <WPEFramework::OCDMProxyStubRegistration>) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/ocdm/ProxyStubs.cpp:1796
#7  0x00007f138516a245 in __static_initialization_and_destruction_0(int, int) (__initialize_p=<optimized out>, __initialize_p@entry=1, __priority=<optimized out>, __priority@entry=65535) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/ocdm/ProxyStubs.cpp:1810
#8  0x00007f138516a50a in _GLOBAL__sub_I_ProxyStubs.cpp(void) () at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/ocdm/ProxyStubs.cpp:1819
#9  0x00007f138e19bdea in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffb2f9c1f8, env=env@entry=0x614000000440) at dl-init.c:72
#10 0x00007f138e19beea in call_init (env=0x614000000440, argv=0x7fffb2f9c1f8, argc=1, l=<optimized out>) at dl-init.c:30
#11 0x00007f138e19beea in _dl_init (main_map=main_map@entry=0x61a000020480, argc=1, argv=0x7fffb2f9c1f8, env=0x614000000440) at dl-init.c:119
#12 0x00007f138e19fecf in dl_open_worker (a=a@entry=0x7f1388ffc1f0) at dl-open.c:506
#13 0x00007f138c9e7067 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:196
#14 0x00007f138e19f73e in _dl_open (file=0x611000010080 "/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/wpeframework/plugins/libWPEFrameworkOCDM.so", mode=-2147483647, caller_dlopen=0x7f138d42a034 <__interceptor_dlopen(char const*, int)+228>, nsid=<optimized out>, argc=1, argv=0x7fffb2f9c1f8, env=0x614000000440) at dl-open.c:588
#15 0x00007f138d39539a in dlopen_doit (a=a@entry=0x7f1388ffc410) at dlopen.c:66
#16 0x00007f138c9e7067 in __GI__dl_catch_exception (exception=exception@entry=0x7f1388ffc3b0, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:196
#17 0x00007f138c9e7103 in __GI__dl_catch_error (objname=0x6030000078e0, errstring=0x6030000078e8, mallocedp=0x6030000078d8, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:215
#18 0x00007f138d395b09 in _dlerror_run (operate=operate@entry=0x7f138d395340 <dlopen_doit>, args=args@entry=0x7f1388ffc410) at dlerror.c:163
#19 0x00007f138d39543a in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#20 0x00007f138d42a034 in __interceptor_dlopen(char const*, int) (filename=0x611000010080 "/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/wpeframework/plugins/libWPEFrameworkOCDM.so", flag=1) at ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:5576
#21 0x00007f138ce54817 in WPEFramework::Core::Library::Library(char const*) (this=0x7f1388ffced0, fileName=0x611000010080 "/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/_install/usr/lib/wpeframework/plugins/libWPEFrameworkOCDM.so") at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/core/Library.cpp:22
#22 0x000000000068d770 in WPEFramework::PluginHost::Server::Service::CheckLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, unsigned int) (this=<optimized out>, this@entry=0x61a000004880, name=..., className=<optimized out>, className@entry=0x7f1388ffd140 "OCDM", version=<optimized out>, version@entry=4294967295) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/WPEFramework/PluginServer.h:1025
#23 0x000000000068e253 in WPEFramework::PluginHost::Server::Service::AquireInterfaces() (this=<optimized out>, this@entry=0x61a000004880) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/WPEFramework/PluginServer.h:1066
#24 0x0000000000663bcf in WPEFramework::PluginHost::Server::Service::Activate(WPEFramework::PluginHost::IShell::reason) (this=<optimized out>, why=<optimized out>) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/WPEFramework/PluginServer.cpp:359
#25 0x00007f138d2e5f36 in WPEFramework::PluginHost::IShell::Job::Dispatch() (this=0x604000003090) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/plugins/IShell.h:88
#26 0x000000000066daf3 in WPEFramework::Core::Job::Dispatch() (this=this@entry=0x61a000002d70) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/WPEFramework/../core/Thread.h:350
#27 0x00000000006f373b in WPEFramework::Core::ThreadPoolType<WPEFramework::Core::Job, (unsigned short)3, 2147483647u>::ThreadUnitType<WPEFramework::Core::Job>::Worker() (this=<optimized out>) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/WPEFramework/../core/Thread.h:449
#28 0x00007f138cea0c2c in WPEFramework::Core::Thread::StartThread(WPEFramework::Core::Thread*) (cClassPointer=<optimized out>) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/core/Thread.cpp:143
#29 0x00007f138c88758e in start_thread (arg=<optimized out>) at pthread_create.c:486
#30 0x00007f138c9aa683 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

Frame 4:
```
(gdb) fr 4
#4  0x00007f13851857cb in WPEFramework::ProxyStub::UnknownStubType<OCDM::ISessionExt, &WPEFramework::SessionExtStubMethods>::UnknownStubType (this=0x602000002d10) at /home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/2/WPEFramework/Source/core/../com/IUnknown.h:49
49	            while (METHODS[_myHandlerCount] != nullptr) {
(gdb) p _myHandlerCount
$1 = 13
(gdb) p METHODS[12]
$2 = (WPEFramework::ProxyStub::MethodHandler) 0x7f13851685bc <WPEFramework::<lambda(WPEFramework::Core::ProxyType<WPEFramework::Core::IPCChannel>&, WPEFramework::Core::ProxyType<WPEFramework::Core::IPCMessageType<2, WPEFramework::RPC::Data::Input, WPEFramework::RPC::Data::Output> >&)>::_FUN(WPEFramework::Core::ProxyType<WPEFramework::Core::IPCChannel> &, WPEFramework::Core::ProxyType<WPEFramework::Core::IPCMessageType<2, WPEFramework::RPC::Data::Input, WPEFramework::RPC::Data::Output> > &)>
(gdb) p METHODS[13]
$3 = (WPEFramework::ProxyStub::MethodHandler) 0x0
```
Based on above it looks that METHODS[13] access generates kind of array-index-out-of-bounds-exception using Java nomenclature.

I haven't observed that on a previous version _(roughly month ago)_ so it must be a relatively new regression.

**Comment by pwielders** [comment]
@dwrobel As the ProxyStubs are now generated automatically and the RPC mechanism has been refactored to support of-host instantation, could you retry this test with the latest-greatest?

**Comment by woutermeek** [comment]
@dwrobel is this still an issue or can we close it?

**Comment by woutermeek** [comment]
@dwrobel closing this issue. If this issue still occurs please create a new issue.
